import type { StrumPattern } from './arrange';
import type { SongTab, TabBar } from './tab';

/** Display order for tablature: high E on top, as it is written on paper. */
const STRING_LABELS = ['e', 'B', 'G', 'D', 'A', 'E'];

function chordAtOffset(bar: TabBar, offsetBeats: number) {
  for (const slot of bar.slots) {
    if (offsetBeats >= slot.offsetBeats - 1e-6 && offsetBeats < slot.offsetBeats + slot.beats - 1e-6) {
      return slot.event.chord;
    }
  }
  return bar.slots.length ? bar.slots[bar.slots.length - 1].event.chord : null;
}

export interface BarTab {
  /** Six rows, high E first, each already padded to the same width. */
  rows: string[];
  /** Strum directions, aligned under the rows. */
  directions: string;
  /** Chord names, aligned over the rows. */
  names: string;
}

/**
 * Six-line tablature for one bar under a strumming pattern.
 *
 * Every column is one strum, so the tab shows rhythm as well as pitch — which
 * is the part a chord chart alone leaves out and beginners most often get wrong.
 */
export function barTab(bar: TabBar, strum: StrumPattern): BarTab {
  const steps = strum.steps.filter((s) => s.beat < bar.beats);
  const columns = steps.map((step) => {
    const chord = chordAtOffset(bar, step.beat);
    const cells = chord
      ? chord.shape.frets.map((f) => (f < 0 ? 'x' : String(f)))
      : new Array(6).fill('-');
    return { cells, step, chord };
  });

  const width = Math.max(1, ...columns.flatMap((c) => c.cells.map((cell) => cell.length)));
  const pad = (text: string): string => text.padStart(Math.floor((width - text.length) / 2) + text.length, '-').padEnd(width, '-');

  const rows = STRING_LABELS.map((label, displayIndex) => {
    const stringIndex = 5 - displayIndex; // rows run high E to low E
    const body = columns.map((c) => pad(c.cells[stringIndex])).join('--');
    return `${label}|-${body}-|`;
  });

  const prefix = ' '.repeat(STRING_LABELS[0].length + 2);
  const directions = prefix + columns.map((c) => center(c.step.direction, width)).join('  ') + ' ';
  const names =
    prefix +
    columns
      .map((c, i) => {
        const previous = i > 0 ? columns[i - 1].chord : null;
        const changed = i === 0 || c.chord?.label !== previous?.label;
        return center(changed ? (c.chord?.label ?? 'N.C.') : '', width);
      })
      .join('  ') +
    ' ';

  return { rows, directions, names };
}

function center(text: string, width: number): string {
  if (text.length >= width) return text;
  const left = Math.floor((width - text.length) / 2);
  return ' '.repeat(left) + text + ' '.repeat(width - text.length - left);
}

/**
 * The whole tab as plain text, for pasting anywhere.
 *
 * Chord charts live in forum posts and notes apps far more than in any one
 * tool, so the output has to survive being copied out of this one.
 */
export function songTabText(tab: SongTab, title: string): string {
  const lines: string[] = [];
  lines.push(title);
  lines.push('='.repeat(Math.max(4, title.length)));
  lines.push('');
  lines.push(`Key: ${tab.key.name}`);
  lines.push(`Tempo: ${Math.round(tab.tempo)} BPM, ${tab.beatsPerBar}/4`);
  lines.push(tab.capo > 0 ? `Capo: fret ${tab.capo} (play in ${tab.shapeKeyName})` : 'Capo: none');
  lines.push(`Strum: ${tab.strum.name}`);
  lines.push('');

  if (tab.palette.length) {
    lines.push('Chords you need');
    lines.push('---------------');
    for (const chord of tab.palette) {
      const frets = chord.shape.frets.map((f) => (f < 0 ? 'x' : String(f))).join(' ');
      const sub = chord.substitutedFrom ? `  (in place of ${chord.label})` : '';
      lines.push(`  ${chord.shapeLabel.padEnd(7)} ${frets}${sub}`);
    }
    lines.push('');
  }

  if (tab.loop) {
    lines.push(`The loop (${tab.loop.length} bars, ${Math.round(tab.loop.coverage * 100)}% of the song)`);
    lines.push('  | ' + tab.loop.bars.join(' | ') + ' |');
    lines.push('');
  }

  lines.push('Chord chart');
  lines.push('-----------');
  const perLine = 4;
  for (let i = 0; i < tab.bars.length; i += perLine) {
    const group = tab.bars.slice(i, i + perLine);
    lines.push(
      `${String(i + 1).padStart(3)}  ` +
        group.map((bar) => '| ' + (bar.signature || 'N.C.').padEnd(16)).join('') +
        '|',
    );
  }
  lines.push('');

  const sample = tab.bars.slice(0, Math.min(tab.bars.length, tab.loop?.length ?? 4));
  if (sample.length) {
    lines.push('Tablature (one time through)');
    lines.push('----------------------------');
    for (const bar of sample) {
      const rendered = barTab(bar, tab.strum);
      lines.push(rendered.names);
      lines.push(...rendered.rows);
      lines.push(rendered.directions);
      lines.push('');
    }
  }

  lines.push('Generated by geetab. Chords are a machine transcription — trust your ears over them.');
  return lines.join('\n');
}
